# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [1]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [2]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [29]:
# Generate your random numbers
#np.random.seed(1) #Seed generated for reproducibility

np.random.seed(10)
arr1=np.random.choice(100,15)
print(arr1)
 
np.random.seed(30)
arr2=np.random.choice(100,5)
print(arr2)

np.random.seed(4)
arr3=np.random.choice(100,5)
print(arr3)

#newarray = np.

myarray = arr1.reshape(5,3)
myarray

myarray.shape



#YOUR CODE HERE
#arr 1 = [np.random.seed(
#arr = np.array([np.random.seed(1)] [np.random.seed(1)])

# Print out the array
#myarray

[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54]
[37 37 45 45 12]
[46 55 69  1 87]


(5, 3)

### 1.2 Solution - Run the following cell to check your answer.

In [30]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [53]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

newweight = np.multiply(weight,703) 
print(newweight)

newheight = np.power(height, 2)
print(newheight)

intnewheight = newheight.astype(int)
intnewheight.dtype

intnewweight = newheight.astype(int)
intnewweight.dtype



np.ndarray(intnewweight/intnewheight)
#newheight = (height**2)
#print(newheight)


#BMI = (703*weight)/(height**2)

[119510 126540 133570 140600]
[ 3025 14400  8100 10000]


TypeError: 'numpy.float64' object cannot be interpreted as an integer

### 1.3 Solution: Run the following cell to check your answer.

In [13]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [128]:
x = int(input("x"))
y = int(input( "y"))
a = int(input("a"))
b = int(input("b"))
c = int(input("c"))



np.random.seed(a)
arr1=np.random.choice(x,y)
print(arr1)
 
np.random.seed(b)
arr2=np.random.choice(x,y)
print(arr2)

np.random.seed(c)
arr3=np.random.choice(x,y)
print(arr3)

#newarray = np.

my_func = arr1.reshape(5,3)
my_func


#np.random.seed(z)
#my_func=np.random.choice(x,y)





#my_func = np.array(np.random.choice(x,y), ndmin=z) 
print(my_func)




[37 12 72  9 75  5 79 64 16  1 76 71  6 25 50]
[40 15 72 22 43 82 75  7 34 49 95 75 85 47 63]
[24  3 56 72  0 21 19 74 41 10 21 38 96 20 44]
[[37 12 72]
 [ 9 75  5]
 [79 64 16]
 [ 1 76 71]
 [ 6 25 50]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [130]:
# 1. Return the first row:
my_func[0, :]

array([37, 12, 72])

In [131]:
# 2. Return the last column
my_func[:,-1]

array([72,  5, 16, 71, 50])

In [134]:
# 3. Return the third column values from the 4th and 5th rows
my_func[3,2], my_func[4,2]


(71, 50)

In [135]:
# 4. Multiply every value in the array by 2
multimy_func = np.multiply(my_func, 2)
multimy_func

array([[ 74,  24, 144],
       [ 18, 150,  10],
       [158, 128,  32],
       [  2, 152, 142],
       [ 12,  50, 100]])

In [136]:
# 5. Divide every value by 3
divmy_func=np.divide(my_func,3)
divmy_func

array([[12.33333333,  4.        , 24.        ],
       [ 3.        , 25.        ,  1.66666667],
       [26.33333333, 21.33333333,  5.33333333],
       [ 0.33333333, 25.33333333, 23.66666667],
       [ 2.        ,  8.33333333, 16.66666667]])

In [138]:
# 6. Increase the values in the first row by 12
#my_func[0,:] + [12]

my_vec = my_func [0,]+ 12
my_vec

array([49, 24, 84])

In [154]:
# 7. Calculate the mean of the first column
my_func_column1_sum = sum(my_func[:, 0])
my_func_column1_sum

my_func_column1_len = len(my_func[:,0])
my_func_column1_len

my_func_column_mean = my_func_column1_sum/my_func_column1_len
my_func_column_mean


26.4

In [171]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array

np. min(my_func) 
my_func_min  = np.delete(my_func, np.where(my_func == 1))
np.min(my_func)
my_func_min2  = np.delete(my_func_min, np.where(my_func_min == 1))
my_func_min2
my_func_min

print(np.median(my_func_min2))
print(np.median(my_func))






57.0
37.0


In [174]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array

np.random.seed(2)
newarr1=np.random.choice(100,20).reshape(5,4)
print(newarr1)


[[40 15 72 22]
 [43 82 75  7]
 [34 49 95 75]
 [85 47 63 31]
 [90 20 37 39]]


In [182]:
# 10. Return values in the second column greater than 25
print(newarr1[:,1])
greater_than_25 = newarr1[:,1 ] > 25
greater_than_25
print(greater_than_25)

[15 82 49 47 20]
[False  True  True  True False]


In [184]:
# 11. Return values < 40 in the array


print(newarr1[newarr1 < 40])

[15 22  7 34 31 20 37 39]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [185]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[67  4 42]
 [51 38 33]
 [58 67 69]
 [88 68 46]
 [70 95 83]]


1. The first row:  [67  4 42]


2. The last column:  [42 33 69 46 83]


3. The 3rd column, 4th & 5th rows:  [46 83]


4. Multiply by 2: 
 [[134   8  84]
 [102  76  66]
 [116 134 138]
 [176 136  92]
 [140 190 166]]


5. Divide by 3: 
 [[22.33333333  1.33333333 14.        ]
 [17.         12.66666667 11.        ]
 [19.33333333 22.33333333 23.        ]
 [29.33333333 22.66666667 15.33333333]
 [23.33333333 31.66666667 27.66666667]]


6. Add 12 to the first row: 
 [79 16 54]


7. The mean of the 1st column:  66.8


8. The median after removing the 2 smallest values:  67.0


9. The standard deviation is:  25.066331755051856


10. All values in 2nd column > 25: 
 [[31 66 80]
 [52 76 50]
 [ 4 90 63]
 [79 49 39]]


11. All values < 40: 
 [31  4 39  8]
